include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_print: false
    avoid_classes_with_only_static_members: false
    use_setters_to_change_properties: false
    prefer_constructors_over_static_methods: false
    unnecessary_this: false
    prefer_interpolation_to_compose_strings: false

    type_annotate_public_apis: true
    avoid_redundant_argument_values: false
    # new
    avoid_unused_constructor_parameters: true
    prefer_const_constructors: true
    lines_longer_than_80_chars: true

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/generated/**/*
  enable-experiment:
    - non-nullable
    - extension-methods
  errors:
    missing_return: error
