include: package:lint/analysis_options.yaml
linter:
  rules:
    avoid_print: false
    avoid_classes_with_only_static_members: false
    use_setters_to_change_properties: false
    prefer_constructors_over_static_methods: false
    unnecessary_this: false

    type_annotate_public_apis: true
    avoid_redundant_argument_values: true

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/generated/**/*
  enable-experiment:
    - non-nullable
    - extension-methods
  errors:
    missing_return: error
