name: Flutter Web

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build and deploy Flutter web
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      
      - run: flutter channel master
      - run: flutter upgrade

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter packages get

      #- name: Run code generation
      #  run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build web
        run: flutter build web --release --dart-define=FLUTTER_WEB_CANVASKIT_URL=/snippet_generator/canvaskit_0.25.0/

      # Runs a single command using the runners shell
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.commit_secret}}
          publish_dir: ./build/web
